sonar.projectKey=kisa-mern-10pshine
sonar.projectName=KISA MERN Notes App

sonar.sources=backend/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000